import Action from '../constants/action';

export function fetchPostsSucceeded() {
  return {
    type: Action.FETCH_POSTS_SUCCEEDED,
    posts: [
        {
            "id": 1,
            "category": 1,
            "name": "胡椒",
            "nameEN": "PEPPER",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "梵名“味履支”，又名古月、黑川、白川，多年生藤本植物，原产热带亚洲，浆果球形，黄红色，依成熟及烘焙度的不同而有绿色、黑色、红色及白色四种，有粉状、碎粒状和整粒三种使用形式，在烹调中有去腥压臊、增味提香的作用。一般将整粒胡椒用在肉类、汤类、鱼类及腌渍类等食品的调味和防腐中，在加入香料和卤汁时用粉状较多。",
            "usefulParts": "",
            "medicalProperties": "胡椒味辛温而芳香，可温中散寒、理气止痛、止泻、开胃、解毒，可治胃寒之痛，受寒泄泻，食欲不振。",
            "storageandchoice": "选购时注意以颗粒均匀、饱满、洁净、干燥者为佳，胡椒及其制品胡椒粉，均宜放在干燥及空气流通处，切忌受潮。粉状胡椒的辛香气味易挥发掉，因此保存时间不宜太长。 "
        },
        {
            "id": 2,
            "category": 1,
            "name": "花椒",
            "nameEN": "CHINESE PEPPER",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "花椒属芸香料灌木或小乔木植物，果实呈红色，种子黑色，果实为花椒，含挥发油，性热，味辛香，作为中国特有的香料，在明末辣椒传入中国以前，花椒就已与姜、茱蔡并称为中国民间三大辛辣调料，花椒树因为结实累累，香气浓郁，因此被古人视作多子多福的象征，并用它祭祀祖先、迎神、驱疫、花椒按其颜色青绿色、麻味较强，有一种特殊的清麻香味，多用于麻味较重的菜品，如“火锅”“水煮鱼”“毛血旺”等，红袍椒属于较大众且运用最广的一种，狗椒由于其色泽、香味、麻味都较差，含籽多，所以一般不用或少用。 <br/>花椒味辛性温、能温中散寒，在烹调中具有异味增香味的效用，还能与辣椒、盐等调料综合形成一种麻辣醇厚的复合味。",
            "usefulParts": "",
            "medicalProperties": "花椒除了味道好可作为调味料之外，其药用功效也很重要，如开胃、健脾、理气、止泻、驱除蛔虫、治风湿、关节炎、呕吐、腹泻、感冒、牙痛，对多种细菌有明显抑制作用，能局部麻醉止痛，可促进性机能作用、抗衰老、增强内分泌腺机能等。",
            "storageandchoice": "选用花椒时注意以粒大均匀，气味麻香浓郁，籽少或无籽全干品为佳。购买花椒时，买整粒的比买粉末要好，因为磨成粉末的花椒香味容易散失。整粒的在使用前，先放在干燥的锅里用最小火加温烘炒，花椒里的油质因遇热挥发出来，再碾碎或磨粉以烹调菜肴。 <br/>花椒最忌潮湿，宜用透气性能好的麻布袋存在干燥通风处，颗粒在密封状态下可储放2年之久。 "
        },
        {
            "id": 3,
            "category": 1,
            "name": "姜",
            "nameEN": "GINGER",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "又称生姜，原多年生草本植物，一年生栽培，原产于印度尼西亚，须根不发达，块茎肥大，呈不规则掌状，灰白或黄色，可做蔬菜，调料，亦可用药，姜一切开就有香气，来源在于成分中的挥发油类，辣味成分则为姜辣素，素的年龄不同，姜辣素所含比例也不同，导致生姜和干姜吃起来味道有异。生姜效用偏重的发汗、止沤和解毒，烘干或晒干的干姜则能温中散寒，夏季产的子姜是姜的嫩芽，适合切丝生食。 ",
            "usefulParts": "",
            "medicalProperties": "姜含有挥发性姜油酮和姜油酚，能驱毒去邪，温热中肠，具有适血、祛寒、除湿、发汗等功能，此外还有健胃止呕、辟腥臭、消水肿之功效，故医家和民谚称“家备小姜，小病不慌”。",
            "storageandchoice": "最佳的贮存方式是将买回的鲜姜洗净后，埋入盐罐里，可保持较长的时期不干，但要注意，腐烂的生姜中含有毒物质黄樟素，其对肝脏有害，所以一旦发现生姜腐烂就一定不能食用。 <br/>妙方：<br/>1、鲜姜榨汁可缓解胃溃疡，十二指肠溃疡的食后疼痛。 <br/>2、外出旅游，出发前口嚼生姜服下或贴一片在肚脐上，也可放鼻旁嗅闻，有防晕车晕船之效。",
        },
        {
            "id": 4,
            "category": 1,
            "name": "辣椒",
            "nameEN": "CHILIES",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "茄科多年生木本植物，原产于中南美洲和印度西部，15世纪传入欧洲，明代传入中国，现在全球热带地区都有种植，种类多不胜数，知名的已超过了200多种，是分布最广的香料植物。辣椒是辣味调料的代表，除了辣味外，几乎没有其它味道，最辣的部分是子粒及其旁边的白色脉络，至于辣的程度，则因品种而异。辣椒未成熟时外表为绿色，成熟后转红、杏、黄、紫等不同颜色，外型有长有圆，大小亦不一，其中以手指大小的鲜红色为最普遍食用。成熟的辣椒有各式各样的制法和食法。除可生食或炒食外，辣椒干制后可压成粗碎、片状、粉末状，制成烹调香料，如辣椒粉、辣椒油、辣椒酱等加工品，具有杀菌去腥的效果。 ",
            "usefulParts": "",
            "medicalProperties": "辣椒味辛，能温中下气，开胃祛寒，散风活血，对于抵御潮温、受凉等气候引起的疾病，有独特功效。 ",
            "storageandchoice": "选购辣椒时，以成熟、干爽、坚硬、重身、表面光滑无瑕的为优质，保存时可把辣椒洗净吹干后用纸巾包裹，放进冰箱，可贮存2至3个星期。 ",
        },
        {
            "id": 5,
            "category": 1,
            "name": "丁香",
            "nameEN": "CLOVE",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "最早原产地是印尼摩鹿加群岛（MOLUCCAS）。又叫鸡舌、丁子香，是丁香树结的花苞在未开花之前采摘下来，经干燥后做成的香料。丁香很适合于甜或浓味的食物，美国人常用来撒在烧烤类食物上：而欧洲人喜欢把丁香插在柑橘上，用丝带绑起吊挂在衣橱内以熏香衣物；非洲人喝咖啡时，喜欢加入丁香同煮。丁香还不只这些用途，举凡烹调肉类、腌泡菜、烘焙糕点、调制甜酒，全都可以加入丁香香料。 ",
            "usefulParts": "",
            "medicalProperties": "香精油可作为消毒剂和止痛剂，调稀的丁香油可做漱口剂，将精油擦在齿龈上可解除牙痛。",
            "storageandchoice": "购买丁香时，最好是买整粒的，因粉状丁香的香味极易氧化散失，不易保存，买整粒的就可除去这些缺点，丁香最好的品质外观通常是大粒、圆胖、深咖啡色微带红黄，富含油质，茎梗不超过0.5寸为佳。",
        },
        {
            "id": 6,
            "category": 1,
            "name": "肉豆蔻",
            "nameEN": "NUTMEG",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "来自一种热带常绿乔木，果实中央核仁部分就是肉豆蔻，散发着甘甜而刺激的芳香，口味微苦涩，充满着异国情调。整颗肉豆蔻用擦菜板擦碎后，是汉堡等绞肉食品常用的调味料，也适合于西式糕点。",
            "usefulParts": "",
            "medicalProperties": "公元十六世纪时，肉豆蔻不仅是欧亚间主要商品之一，在中国和阿拉伯地区更是治疗消化病症的药材。",
            "storageandchoice": "肉豆蔻有着坚硬的核仁，可保存较长时间，而其浓烈的香气，在菜肴中只要放一点就味道十足。一般来说肉豆蔻粉可保存8个月之久，而原颗粒则可储放2年以上。"
        },
        {
            "id": 7,
            "category": 1,
            "name": "豆蔻皮",
            "nameEN": "MACE",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "被覆在肉豆蔻黑色外壳上的深红色网状假种皮，就是豆蔻皮，经日晒后，和肉豆蔻一样当作香料使用，两者的香味十分相似，但豆蔻皮的香味要清淡许多，常用于绞肉食品、香肠、甜甜圈等食物当中。",
            "usefulParts": "",
            "medicalProperties": "",
        },
        {
            "id": 8,
            "category": 1,
            "name": "肉桂",
            "nameEN": "CINNAMON",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "肉桂又称为玉桂、丹桂或桂皮，是最早被人类使用的香料之一。全世界的肉桂树大约有上百种，其中2种居领导地位且甚具商业价值的是锡兰肉桂和中国肉桂。锡兰肉桂比较软甜、风味绝佳，桂皮呈浅棕色而且比较薄。 <br/>中国肉桂（桂皮CASSIA）香味比较刺激，树皮较肥厚，颜色较深，芳香也较前者略逊一筹。肉桂的味道芳香而温和，适用于甜和浓味菜肴，特别适合用来煮羊肉，也可以用来做蜜饯水果（特别是梨）、巧克力甜点、糕饼和饮料。肉桂除了有树皮卷成的所谓肉桂棒、肉桂粉外，还有肉桂油出售。新鲜肉桂粉香气比肉桂棒浓重许多，在烹调时，如果不想味道太重，或是不想使食物中有肉桂粉末颗粒，则可使用肉桂棒烹煮后丢弃。深爱肉桂香的人，可以自制肉桂茶，只要用250亳升的开水浸泡约1克重的肉桂树皮丝10分钟，即可饮用。",
            "usefulParts": "",
            "medicalProperties": "",
            "storageandchoice": "买回的肉桂无论皮或粉，只要密封放在干燥，阴凉，黑暗且通风的地方，就可保持1至2年，品质、香气不会逸散变质。",
        },
        {
            "id": 9,
            "category": 1,
            "name": "大蒜",
            "nameEN": "GARLIC",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "大蒜属百合科植物，原产于亚洲中部，其繁殖方法不是用种子，而是用蒜瓣繁殖成一个长有外膜的大蒜球。大蒜味辛性温，有强烈的气味及味道，可用作蔬菜、调味菜或香料，有促进食欲的作用，其所含的蒜辣素有杀菌去腥的作用。大蒜的鳞茎干燥后，气味和刺激性不像新鲜的蒜头那样浓烈，香味又能长期保存，使用时很方便。可加工成蒜片、粗蒜粒、蒜粉、蒜泥等制品，可依据需要分别使用。 ",
            "usefulParts": "",
            "medicalProperties": "有促进食欲的作用，其所含的蒜辣素有杀菌去腥的作用。",
        },
        {
            "id": 10,
            "category": 2,
            "name": "八角茴香",
            "nameEN": "STAR ANISE FRUIT",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "八角的香味接近大茴香，但与大茴香并不属于同科植物，其气味稍含丁香和甘草的芳香，味微苦、甜、八角在中餐中扮演相当重要的角色，多用来去腥增香，通常用于炖菜或焖菜中的提味，亦是中国五香粉的主要万分。在南欧地区，除了各式汤类蔬肉的烹调外，八角亦被大量用作甜点酒饮的添香物。",
            "usefulParts": "",
            "medicalProperties": "八角性辛，温。归肝、肾、脾、胃经。主治温阳散寒、理气止痛。用于寒疝腹痛，肾虚腰痛，胃寒呕吐，脘腹冷痛。还具有开胃、下气、散寒、驱虫、兴奋神经的功效。",
            "storageandchoice": "八角茴香的种子蕴藏在豆荚里，由8个果荚组成，呈星形状地排列于中轴上，故名“八角”。其色泽以棕红、鲜艳有光泽为好，粒大饱满、荚边裂缝较大，能看到荚内籽粒、八角完整不碎者为上品。完整原形的八角大约可密封储藏2年，若是八角粉则约可储放8个月到1年，由于八角的香味很浓，所以使用整个八角是很少见的，一般只放1至2片即可。",
        },
        {
            "id": 11,
            "category": 2,
            "name": "小豆蔻",
            "nameEN": "CARDAMOM",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "别名白豆蔻、圆豆蔻，生姜科多年生草本植物。原产于印度南部以及斯里兰卡地区的热带雨林。北欧诸国、中东、印度料理经常使用小豆蔻，由于栽培小豆蔻只能在排水良好、适当的阴凉处，而不能在贫瘠的土地上或有强风的土地上，受诸多条件的限制，使得小豆蔻产量不高，加上其干燥的工序也很复杂，因此它是属于比较昂贵的香料之一，在我国较少用到。 <br/>在烘制过程中因为色泽的处理而有不同颜色，绿豆蔻为自然风干，白豆蔻以二氧化硫漂白，而印度南部及斯里兰卡等原产地以自然光晒豆蔻，所以色泽为淡黄色。在香气品质上以绿色小豆蔻最能保持此原料的风味，原香中带有柠檬香气的秀雅，而黄白二色小豆蔻气味相近。 ",
            "usefulParts": "",
            "medicalProperties": "小豆蔻的芳香甜美又带刺激性，味道辛辣微苦，有治晕车、失眠、口臭、减肥和增强性功能的功效。",
            "storageandchoice": "三色小豆蔻在不剥开壳并存在密闭容器内时，8至12个月内可保有最佳香气。",
        },
        {
            "id": 12,
            "category": 2,
            "name": "大茴香",
            "nameEN": "ANIS/ANISE",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "属香菜科，一年生草本植物，原产于埃及和中东及印度一带，曾是埃及人制作木乃伊的防腐香料之一，也是印度人用来咀嚼的口腔芳香剂。亚洲人喜欢把大茴香加在汤或炖菜中，欧洲人则常在蛋糕、饼干和甜面包中用它来增添香甜味，如果将大茴香制成酒或加在咖啡里，气味非凡。",
            "usefulParts": "",
            "medicalProperties": "大茴香有一种类似甘草的特殊香味，有去痰、镇咳、促食欲、助消化的功效。",
            "storageandchoice": "大茴香存放时间久了容易变味，使用时要捣碎磨细。贮存时应把它放置在阴凉干爽的地方。",
        },
        {
            "id": 13,
            "category": 2,
            "name": "莳萝",
            "nameEN": "DILL",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "别名土茴香、小茴香，属水芹料，一年生草本植物，原产于地中海沿岸、印度，现在世界各地都有栽种。Dill是镇静的意思。 <br/>莳萝叶片鲜绿色，呈羽毛状，种子呈细小圆扁平状，味道辛香甘甜，有水芹科特有的刺激香味，像烧焦般的辛辣味。多用作食用调味，有促进消化之功效，可直接或磨成粉末制成酱料，最常见的用法是撒在鱼类冷盘及烟熏鲑鱼上，以去腥添香或做盘饰，也可加入泡菜、汤品或调味酱。<br/>莳萝的叶子与种子的辛香程度有点不同，种子的气味和味道较强烈，较适用于腌渍或为某些菜式引出额外的味道，如黄瓜泡菜、马铃薯、肉类、黑麦面包、咖喱、烤鱼等；叶子的气味及味道较温和，适宜鱼类、海鲜、蔬菜、调味酱。",
            "usefulParts": "",
            "medicalProperties": "",
            "storageandchoice": "贮存时可将莳萝用塑胶袋包裹，然后放在冰箱，可贮存数天。或把它切碎后混入少量水，贮放于小容器里。",
        },
        {
            "id": 14,
            "category": 2,
            "name": "葛缕子",
            "nameEN": "CARAWAY",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "别名葛蒿、胡荽子、茴香子，是两年生欧芹科草本植物的种子，原产于亚洲，北欧及中欧，现在世界各地广为栽种，但若以消耗量来说，荷兰与德国名列前茅。葛缕子外观很像莳萝，尝起来的味道却道却像小茴香，是种很容易让人混淆的香料；尤其在亚洲，时常与小茴香交错使用，就边厨师也搞不清楚到底何为本尊。在香料市场的交易中，葛缕子也被称为“外国小茴香”，其中的相似处可见一斑。 <br/>褐色的葛缕子种子长度约1/5英寸，至末端渐窄，仿如弯月形。葛缕子带有水果般的清甜芳香，咬碎后却有柠檬皮般的辛辣苦涩，通常用作食用调味，是开胃除腻的佳品。其独特的清香很适合用来去除肉腥臭味，当与水果和蔬菜结合时，葛缕子即会产生少许的柠檬香味。",
            "usefulParts": "",
            "medicalProperties": "葛缕子中助消化、抗微生物、防腐、增进食欲，还能收敛、驱风、利尿、催经、化痰、提神振奋、整肠健胃及滋补驱虫。",
            "storageandchoice": "一般来说无毒无过敏性，但过量使用可能引起皮肤不适。葛缕子原颗保存期约为18个月，细粉约为6至8个月。 ",
        },
        {
            "id": 15,
            "category": 2,
            "name": "芫荽子",
            "nameEN": "CORIANDER",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "芫荽别名胡荽、香菜，属水芹科一年或二年生草本植物，原产于东欧、中东，现在全球都有种植。芫荽的英文名Coriander源自希腊语，意指“臭虫”，原因是芫荽的种子未成熟前，茎叶的味道类似甲虫味般不太好闻，待果实成熟后则转变成类似茴香的辛香味。芫荽的气味一般人在第一次接触时较难忍受，尤其是较少使用芫荽的西方国家。但是在中国与东南亚却大受欢迎。不仅芫荽叶可生食，还经常放在食物或酱汁上做除腥提味的香料，芫荽子更是印度咖喱的原料之一，可以说是万能香料。墨西哥菜中也常用到它。 <br/>芫荽味道温和酸甜，微含辛辣，近似橙皮的味道，并略含未质清香，以及胡椒的风味。芫荽的茎、根、叶用炒等方法加热后，好像有柑桔的香味，但比之加热前，香味已严重流失。",
            "usefulParts": "",
            "medicalProperties": "",
            "storageandchoice": "颗粒的芫荽子外壳很薄，所以应尽量以原颗粒保存，时间可长达1年之久。若研成细粉则只6个月的香气有效期。 "
        },

        {
            "id": 16,
            "category": 2,
            "name": "芹菜子",
            "nameEN": "CELERY SEEDS",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "芹菜别名荷兰鸭儿芹，伞形科两年生植物。古代的药草记录显示，人类种植芹菜至少有3000年历史，尤其是在古埃及，而公元前5世纪的中国早已懂得使用芹菜了。芹菜自古以来被当作一种蔬菜，一般被使用的部分为果实、根与叶子。不过很时候，整株植物跟种子都被当作药物使用。<br/>芹菜的花朵很小，芹菜子就是取自芹菜小小的花朵中，因而种子的体形也非常之小，呈卵形，颜色多为棕褐色或深棕色，具有宜人的浓烈香气，味道微辛而苦。很适合用于制作蔬菜菜肴，尤其在番茄汁中加入少量芹菜子，可以抵消彼此的生青味。在做汤、炖菜、调酱料、烘焙等料理中，芹菜子都是不错的香料。",
            "usefulParts": "",
            "medicalProperties": "芹菜子性温味甘、无毒。其所含的多种有效成分，对风温症、风湿关节炎、痛风、高尿酸症等都有舒解作用，也是极佳的利尿剂，对中枢神经系统有镇静安神作用，能舒解胀气及消化不良的毛病，还能起到降血压，降血糖作用。",
        },
        {
            "id": 17,
            "category": 2,
            "name": "葫芦巴",
            "nameEN": "FENUGREEK",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "别名苦豆、香草，一年生草本植物，为豆科植物戎芦巴的种子。我国的安徽、四川河南等地多有栽培。葫芦巴可以用来制作咖喱粉，也可以萃取其种子中的葫芦蔬全株都有香气，除了种子，嫩叶也可以用来烹调。 <br/>种子路呈斜方形，表面黄棕色或红棕色，微有灰色短毛，两侧各有一深斜沟，两沟相接处为种脐。质坚硬、气香、味微苦。种子晒干后可直接生用，或微妙用。磨碎后的种子会产生类似焦糖般的苦味以及芹菜般的甘香。将种子稍微烘烤再磨碎，焦糖般的香味会更明显，但如果将种子放进煮沸的酒里再取出晾干，这种味道就会除净。",
            "usefulParts": "",
            "medicalProperties": "葫芦巴性温，味苦。可温肾，祛寒，止痛。用于肾脏虚冷、小腹冷痛，小肠疝气、寒湿脚气。 ",
        },
        {
            "id": 18,
            "category": 2,
            "name": "罂粟子",
            "nameEN": "POPPY SEEDS",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "罂粟科一年生草本植物，原产于亚洲，现在欧洲及美洲均有栽培。罂粟子是罂粟植物上荚果的种子，略带有坚果味，可广泛用于多种菜肴。在欧洲及中东，罂粟子被用于面包、蛋糕、馅包、饼干等；在土耳其，通常磨碎后用于甜点；在印度，也是磨碎后混入酱料；在德国、斯拉夫民族，通常用于面食、蔬菜、鱼类菜肴中。<br/>一般常见的罂粟子是深蓝带灰（看起来很似黑色，比芝麻还小），硬且圆，有淡核味。烘焙用的罂粟子经过干燥和烘焙之后，已经没有毒性；但在我国台湾地区因考虑种子未经完全干燥和烘焙仍有发芽种植的可能，罂粟子仍被列为毒品管制名单之中。",
            "usefulParts": "",
            "medicalProperties": "",
        },
        {
            "id": 19,
            "category": 2,
            "name": "芝麻",
            "nameEN": "SESAME",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "别名胡麻子，为脂麻科一年生草本植物脂麻的成熟种子，芝麻依其种子外皮的颜色，可分为黑芝麻、白芝麻和黄芝麻，中国常见的是黑白两种，黄芝麻由于全世界的产量不多，因而非常昂贵。芝麻的营养非常丰富，含有脂肪油、蛋白质、蔗糖、卵磷脂等多种营养成分，生嚼，炒食，磨酱，榨油或做糕饼糖果配料皆可。香喷喷的芝麻或做点心吃，或榨油食用，都不失为佳品。通常食用以白芝麻为好，药用则以黑芝麻为佳。 <br/>黑芝麻的种子呈扁卵圆形，表面为黑色，味道甘甜，有油香气。黑芝麻比白芝麻香气更浓，但含油量比白芝麻低，主要用制作糕点、芝麻酱等。 <br/>白芝麻是种子呈白色的品种，其油脂含量是芝麻中最高的。除了烹调，主要供应榨油。 <br/>黄芝麻的种子是金黄色的，也称“黄金芝麻”，是芝麻中香气最强的品种。 ",
            "usefulParts": "",
            "medicalProperties": "芝麻性平，味甘，无毒。补肝肾，益精备，润肠燥，可防治头晕眼花、耳鸣耳聋、须发早白、病后脱发、养血增乳。",
            "storageandchoice": "保存时要注意存放在通风干燥处，天热时宜放阴凉处，防止走油。 ",
        },
        {
            "id": 20,
            "category": 2,
            "name": "芥末",
            "nameEN": "MUSTARD",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "别名芥子、芥菜子、胡芥。属十字花科，一年生草本植物，原产亚洲。芥末有黑、白、褐三色，其中黑芥末味道较辛辣刺激，白芥末辛辣味相对温和芳香，通常说的芥末即是黑芥末即是黑芥菜和白芥菜两大灌木的种子；褐芥末则主要产于印度。 <br/>芥菜子可直接使用或捣成粉末后使用，干芥菜子并不辣，需加水才会反应出辛辣物质，时间愈入愈辣，但放置太久，香与辣会散失。加温水可加速酵素活性，会更辣。粉状芥末也如此，变干后会失去香味，若把芥末混水做成酱，则可散发其辛辣味。芥末可用于各种烹调料理中，白芥末尤其得到广泛适用。如牛肉、猪肉、羊肉、鱼肉、鸡肉、鸟肉、沙律、酱料、甜点等，用于去腥提味，也可原粒用来腌菜或放入沸水中煲煮蔬菜。还可用于调制香肠、火腿、沙拉酱、糕饼等。 ",
            "usefulParts": "",
            "medicalProperties": "",
            "storageandchoice": "要长久保存芥末酱，可用柠檬汁、酒或葡萄酒等来调制，使其具有酸性，效果相当不错。",
        },

        {
            "id": 21,
            "category": 2,
            "name": "葵花子",
            "nameEN": "SEEDS OF SUNFLOWER",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "别名向日葵，为菊科一年生草本植物，我国各地均有栽培。向日葵一身是药，其种子、花盘、茎叶、茎髓、根、花等均可入药。葵花子仁营养丰富，不含任何不利营养的或有毒的物质。所含的脂肪油达50%以上，其中亚油酸占70%，有良好的降脂和预防慢性高胆固醇血症的作用。除食用外还可专供榨油。<br/>",
            "usefulParts": "",
            "medicalProperties": "葵花子及油还有润肤泽毛之效。葵花子性味甘、温、平。有健脾润肠、息肝风、祛热毒、止痢、治疡肿之功效。还能治失眼、增强记忆力，对预防癌症，高血压和神经衰弱有一定作用。南瓜子可做葵花子的代用品，这种食物尤其适合那些患有前列腺炎的病人。去壳炒过的葵花子仁可当作下酒菜，剁碎后也可加在沙拉里食用。葵花子的加工方法一般有炒、烤、蒸、煮等几种，与瓜子类似。 <br/>老人不宜食葵花子。葵花子含油量高，进食过多会使老年人肝脏负担加重，有可能透发肝炎。还会使血压升高或使高血压病患者症状加剧，严重者还会透发脑中风或心绞痛。多食不宜。葵花子炒后性温燥，多食后易致口干、口疮、牙痛等上火症状，故应注意。 ",
        },
        {
            "id": 22,
            "category": 2,
            "name": "瓜子",
            "nameEN": "SEEDS OF WATERMELON",
            "genusSpecies": "",
            "family": "",
            "origin": "",
            "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
            "introduction": "别名西瓜子、黑瓜子、瓜料一年生草本植物。原产非洲中部，现在世界各地都有栽培。 ",
            "usefulParts": "",
            "medicalProperties": "瓜子表皮颜色呈黑色，瓜子仁富含脂肪、蛋白质和多种维生素，还含有一种皂甙物质，具有清肺、润肠、和中、止渴、止血、健胃、降压等作用。瓜子除了炒制食用外，还可用作中式点心的馅料。 ",
            "storageandchoice": "识别选购时要一看片型，以片粒均匀、板正平直为佳，反之则低劣。二看壳面，壳面鼓起的子仁饱满，皮壳凹瘪发黄破裂为次。三尝味道，齿嗑易开，子仁胆厚松脆，味道香而鲜美为佳，反之低劣。食用劣的西瓜子会出现喉咙痒、干咳、腹泻等症状，有害身体健康。",
        },
        {
          "id": 23,
          "category": 3,
          "name": "紫苏",
          "nameEN": "BASIL",
          "genusSpecies": "",
          "family": "",
          "origin": "",
          "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "introduction": "紫苏也称罗勒，是一种生长在东半球温暖地带的一年生薄荷类植物。紫苏原名出自希腊文，意为“皇室之香油”，原产于太平洋群岛，十六世纪时由亚洲传到欧洲。全世界的紫苏约有150种之多，叶片有绿色还有紫色，提味效果颇佳。其中荷力罗勒（Holy Basil）及甜罗勒（Sweet Basil）经常加入泰国菜，也可加入沙拉及用作装饰材料。",
          "usefulParts": "",
          "medicalProperties": "",
          "storageandchoice": "紫苏可贮存于冰箱内1天，若要保鲜时间长，可将紫苏用盐腌，并放入装有橄榄油或醋的瓶子，并将瓶盖密封，放入冰箱保存。也可将紫苏叶混合少量水榨成浆汁，注入小瓶，放进冰屉，可贮存6个月，不过会失去紫苏的原味。 "
      },
      {
          "id": 24,
          "category": 3,
          "name": "月桂叶",
          "nameEN": "BAY LEAVES",
          "genusSpecies": "",
          "family": "",
          "origin": "",
          "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "introduction": "月桂叶是原产于南欧地中海沿岸的绿灌木或小乔木，两种月桂叶都是绿色，呈长椭圆披针形，约长3英寸，叶面光滑，带有辛辣及强列苦味，有除腥防腐的功效。欧洲人常用来制作肉类、炖菜的添加香料。<br/>由于月桂叶要在经过加工后，其特有的香气才会充分透散出来，所以月桂叶只在众多香料的搭配下才使用，属于辅佐带叶的配角，不常多放。 ",
          "usefulParts": "",
          "medicalProperties": "",
      },
      {
          "id": 25,
          "category": 3,
          "name": "香葱",
          "nameEN": "CHIVES",
          "genusSpecies": "",
          "family": "",
          "origin": "",
          "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "introduction": "香葱又称为冬葱、大葱，细香葱或四季葱，属百合科葱属，是一种多重生宿根的草木植物，原产地有说是中国，也有说是西亚。香葱为鲜绿色，葱叶长而空心，茎柔细而香，含有较多挥发油，烹调加热后会迅速在空气中释放，为不同菜肴添上美味。 ",
          "usefulParts": "",
          "medicalProperties": "葱含有多种维他命、矿物质，它的热辣芳香还能帮人体祛风发汗，颇具药膳功能，比如：将葱茎或全株捣汁具有散瘀血，止痛，消痣，解毒的功效，葱白连根用水煮服，可祛风发汗，对冬天风寒引起的鼻塞、头痛、发热不流汗等有缓解效果。食疗本草中记载，感冒初期头痛时，中药也有葱豉配方，即以葱白加淡味的豆豉，煮水炖服。",
      },

      {
          "id": 26,
          "category": 3,
          "name": "山艾",
          "nameEN": "SAGE",
          "genusSpecies": "",
          "family": "",
          "origin": "",
          "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "introduction": "山艾又名鼠尾草，属紫苏科植物。草本灌木植物，叶子呈淡紫绿色，呈长形，味香性温，有清草味的苦味。意大利人相当偏爱山艾，当他们购买肉类时，肉贩经常会附送些山艾给顾客。 ",
          "usefulParts": "",
          "medicalProperties": "在古罗马时代，山艾有“救世仙草”的美誉，除可帮助消化外，还能镇静、解热、被普遍用于肉类内脏食品的除腥提味。",
          "storageandchoice": "新鲜的山艾可放入冰箱中用保鲜袋保存3-5天，干燥品则可存1年之久。由于气味浓厚，不论干鲜，入菜都不宜多放。 ",
      },
      {
          "id": 27,
          "category": 3,
          "name": "香茅",
          "nameEN": "LEMON GRASS",
          "genusSpecies": "",
          "family": "",
          "origin": "",
          "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "introduction": "香茅原产于东南亚，现在南美洲、北美洲、澳洲、非洲等地都有种植，叶片幼长，形似韭菜，叶干由嫩叶片层层包裹，带有柠檬及柑桔的清香。干香茅通常用开水冲泡成草茶，只有新鲜的香茅可用来烹煮，使用香茅前，应将根部切除及剥去叶的外皮，让叶片散发香味，亦可将茎部放入水中煲出叶香。如没有香茅，可用柠檬皮做替代品，用香茅草伏成的塞瑞香（Seren Power）可作为沙拉、鱼和汤品的调味料。<br/>香茅在东南亚是一种普遍的烹饪香料，一般将整条或切片放进清汤里，或与其它香料一起搅碎成糊后用来焖食物。煮过的香茅会留下纤维，所以应避免咀嚼它。香茅、辣椒和新鲜的元茜是一种很好的组合。",
          "usefulParts": "",
          "medicalProperties": "",
      },
      {
          "id": 28,
          "name": "荷叶",
          "nameEN": "LOTUS LEAVES",
          "genusSpecies": "",
          "family": "",
          "origin": "",
          "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "introduction": "即莲花叶片，中国人喜欢用荷叶包裹食物或馅料蒸煮，在蒸的过程中，荷叶香会渗入食物中，令食物别有一番风味，如荷叶饭、荷叶蒸虾、荷叶排骨等。蒸熟后将原个端上饭桌，才推开荷叶，食用后把荷叶扔掉。 ",
          "usefulParts": "",
          "medicalProperties": "",
      },
      {
          "id": 29,
          "name": "百里香",
          "nameEN": "THYME",
          "genusSpecies": "",
          "family": "",
          "origin": "",
          "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "introduction": "又名“麝香草”，原产于地中海及西欧地区，属矮形草本植物，叶片亮泽、味道浓郁芳香。干燥的百里香粉或叶片可用于调味香料，与海鲜、肉类及橙叶酱汁十分相配。由于它即使长时间烹调也不失香味，因此非常适合用在炖煮或烤烘上。",
          "usefulParts": "",
          "medicalProperties": "百里香含有杀菌和抗氧化的成分，中世纪的欧洲人还认为其可防止食物腐坏，延长食物的保存期限。",
      },
      {
          "id": 30,
          "name": "胡椒薄荷",
          "nameEN": "PEPPERMINT",
          "genusSpecies": "",
          "family": "",
          "origin": "",
          "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "introduction": "胡椒薄荷可促进肠胃蠕动，帮助消化，并用于制作糕点和香烟。加在羊肉菜肴中，可去除羊肉的膻味。此外，由叶片提取的薄荷精油，则是奶油薄荷酒这种利口酒用来调味的主料。",
          "usefulParts": "",
          "medicalProperties": "",
      },

      {
          "id": 31,
          "name": "香菜",
          "nameEN": "CORIANDER",
          "genusSpecies": "",
          "family": "",
          "origin": "",
          "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
          "introduction": "又名胡荽、芜荽。属欧芹科，一、二年生草本植物，原产地为地中海东部沿岸。香菜呈羽毛状，味甘香甜，传统上用于墨西哥、中东及亚洲菜式，尤其是有在黑西哥式的蘸料烧砂酱及奶油中，用作墨西哥起司碎肉卷饼、塔可、咖喱料理等食品中做香料。",
          "usefulParts": "",
          "medicalProperties": "",
      },
    ],
  };
}
