import Action from '../constants/action';

export function fetchPostsSucceeded() {
  return {
    type: Action.FETCH_POSTS_SUCCEEDED,
    posts: [
      {
        "id": 3,
        "name": "牛至",
        "nameEN": "oregano",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 4,
        "name": "甜红辣椒粉",
        "nameEN": "paprika",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 5,
        "name": "小茴香",
        "nameEN": "cumin",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "莳萝；小茴香（子）；孜然芹",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 6,
        "name": "咖喱粉",
        "nameEN": "garlic powder",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 7,
        "name": "洋葱",
        "nameEN": "onion",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 8,
        "name": "辣椒粉",
        "nameEN": "cayenne pepper",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 9,
        "name": "香菜",
        "nameEN": "coriander",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 10,
        "name": "肉豆蔻",
        "nameEN": "nutmeg",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 11,
        "name": "生姜",
        "nameEN": "ginger",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
    ],
  };
}
