import Action from '../constants/action';

export function fetchPostsSucceeded() {
  return {
    type: Action.FETCH_POSTS_SUCCEEDED,
    posts: [
      {
        "id": 2,
        "name": "藏红花",
        "nameEN": "Saffron",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "香料之王，价格比黄金贵，从花中取三个柱头，75000朵花才产出1磅藏红花，是很好的食用香料，欧洲菜式中多搭配海鲜，也可以当天然着色剂使用。因为价格有利可图，市场充斥着爆多的假货。中国西藏有少量栽培，产量不会很大，而且质量不是最好的，七八十元每克是正常价格，如果比这个价格便宜很多，你懂的。伊朗产的藏红花最佳，市场价格200元左右每克。",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 3,
        "name": "牛至",
        "nameEN": "oregano",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 4,
        "name": "甜红辣椒粉",
        "nameEN": "paprika",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 5,
        "name": "小茴香",
        "nameEN": "cumin",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "莳萝；小茴香（子）；孜然芹",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 6,
        "name": "咖喱粉",
        "nameEN": "garlic powder",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 7,
        "name": "洋葱",
        "nameEN": "onion",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 8,
        "name": "辣椒粉",
        "nameEN": "cayenne pepper",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 9,
        "name": "香菜",
        "nameEN": "coriander",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 10,
        "name": "肉豆蔻",
        "nameEN": "nutmeg",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 11,
        "name": "生姜",
        "nameEN": "ginger",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 13,
        "name": "牛至",
        "nameEN": "oregano",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 14,
        "name": "甜红辣椒粉",
        "nameEN": "paprika",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 15,
        "name": "小茴香",
        "nameEN": "cumin",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "莳萝；小茴香（子）；孜然芹",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 16,
        "name": "咖喱粉",
        "nameEN": "garlic powder",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 17,
        "name": "洋葱",
        "nameEN": "onion",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 18,
        "name": "辣椒粉",
        "nameEN": "cayenne pepper",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 19,
        "name": "香菜",
        "nameEN": "coriander",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 20,
        "name": "肉豆蔻",
        "nameEN": "nutmeg",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
      {
        "id": 21,
        "name": "生姜",
        "nameEN": "ginger",
        "cover": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "coverThumbnail": "https://img3.doubanio.com/view/photo/photo/public/p2401931302.jpg",
        "introduction": "",
        "marriedWith": "",
        "complements": "",
      },
    ],
  };
}
