const Action = {
  FETCH_POSTS_SUCCEEDED: 'FETCH_POSTS_SUCCEEDED',
  SELECT_ITEM: 'SELECT_ITEM',
  NAVIGATE_TO_PAGE: 'NAVIGATE_TO_PAGE',
  NAVIGATE_TO_PREVIOUS_PAGE: 'NAVIGATE_TO_PREVIOUS_PAGE',
};

Object.freeze(Action);

export default Action;
